package com.balabas.smarthouse.server.entity.model;

public enum State {
	UNKNOWN, CONSTRUCTED, REGISTERED, REREGISTERED, CONNECTED, INIT_DATA_RECEIVED, UPDATED, FAILED, TIMED_OUT, DISCONNECTED, OK, BAD_DATA 
}
