/*
 * DeviceConfig.h
 *
 *  Created on: Oct 9, 2019
 *      Author: Vitaliy_Vlasov
 */

#ifndef LIBRARIES_ENTITYLIBSIMPLE_DEVICECONFIG_H_
#define LIBRARIES_ENTITYLIBSIMPLE_DEVICECONFIG_H_

#ifndef SETTINGS_WIFI_SSSID
	#define SETTINGS_WIFI_SSSID "balabasKiev5"
	#define SETTINGS_WIFI_PASSWORD "wuWylKegayg2wu22"
#endif

#ifndef SETTINGS_SMART_SERVER_ADDRESS
	#define SETTINGS_SMART_SERVER_ADDRESS "192.168.0.101"
	#define SETTINGS_SMART_SERVER_KEY "SomeServerKey"
#endif

#define MQTT_PUBLISHER "!!SmartHouse-device"
#define MQTT_HOST "192.168.0.101"
#define MQTT_PORT 1883
#define MQTT_USER "mqttuser"
#define MQTT_PASSWORD "mqttpassword"

#define DEVICE_MANAGER_MIN_HEAP_RESTART 2000
#define REQUEST_SECURITY_DISABLED 1
#define SETTINGS_SERVER_MQTT_DISABLED 1
#define SETTINGS_SERVER_GET_DISPATCH_CHANGES_DISABLED 1

#ifndef SERVER_CONNECTION_REGISTRATION_FAILED_FIRST_TIMEOUT
	#define SERVER_CONNECTION_REGISTRATION_FAILED_FIRST_TIMEOUT 60000
#endif

#ifndef SERVER_CONNECTION_REGISTRATION_FAILED_NEXT_COUNT
	#define SERVER_CONNECTION_NEXT_REGISTRATION_NEXT_COUNT 10
#endif

#ifndef SERVER_CONNECTION_REGISTRATION_FAILED_NEXT_TIMEOUT
	#define SERVER_CONNECTION_REGISTRATION_FAILED_NEXT_TIMEOUT 120000
#endif

#ifndef SERVER_CONNECTION_REGISTRATION_FAILED_MIN_HEAP_TO_RESTART
	#define SERVER_CONNECTION_REGISTRATION_FAILED_MIN_HEAP_TO_RESTART 10000
#endif

class DeviceConfig {
};

#endif /* LIBRARIES_ENTITYLIBSIMPLE_DEVICECONFIG_H_ */
